<a href="https://colab.research.google.com/github/AmitUdugade/PythonWorkspace/blob/main/Numpy_Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#4x4 numpy array whose value set to True

import numpy as np

np.full((4,4), fill_value = True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [2]:
np.ones((4,4), dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
#4x4 numpy array whose diagonal value set to True and rest are false
np.identity(4, dtype = bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [8]:
np.identity(4, dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
#Assignment : 4x4 numpy array whose diagonal value set to False and rest are True


In [17]:
a = np.random.random((4,4))
a.size

16

In [20]:
a.shape
print("Total no. of Rows ", a.shape[0])
print("Total no. of Columns ", a.shape[1])

Total no. of Rows  4
Total no. of Columns  4


In [21]:
#a memory in bytes to each element.
print(a.itemsize)

8


In [22]:
#Check datatype
print(a.dtype)

float64


In [23]:
#Check memory

print(a.data)

In [24]:
#check dimensions

print(a.ndim)

2


In [25]:
#Shape Manipulation -
# reshape - to do changes temporary.

a.reshape(8,2)

array([[0.70240422, 0.65642767],
       [0.38868487, 0.40613288],
       [0.85756771, 0.52449964],
       [0.77800792, 0.32890273],
       [0.75028909, 0.95656555],
       [0.24828801, 0.4873072 ],
       [0.13575261, 0.78794215],
       [0.03214194, 0.81382809]])

In [27]:
a.reshape(16,1)

array([[0.70240422],
       [0.65642767],
       [0.38868487],
       [0.40613288],
       [0.85756771],
       [0.52449964],
       [0.77800792],
       [0.32890273],
       [0.75028909],
       [0.95656555],
       [0.24828801],
       [0.4873072 ],
       [0.13575261],
       [0.78794215],
       [0.03214194],
       [0.81382809]])

In [28]:
a.reshape(4,2,2)

array([[[0.70240422, 0.65642767],
        [0.38868487, 0.40613288]],

       [[0.85756771, 0.52449964],
        [0.77800792, 0.32890273]],

       [[0.75028909, 0.95656555],
        [0.24828801, 0.4873072 ]],

       [[0.13575261, 0.78794215],
        [0.03214194, 0.81382809]]])

In [29]:
a.reshape(2,4,2)

array([[[0.70240422, 0.65642767],
        [0.38868487, 0.40613288],
        [0.85756771, 0.52449964],
        [0.77800792, 0.32890273]],

       [[0.75028909, 0.95656555],
        [0.24828801, 0.4873072 ],
        [0.13575261, 0.78794215],
        [0.03214194, 0.81382809]]])

In [31]:
#resize - To do changes permanantly.
#do the multiple operations 2D, 3D etc.
a.resize(16)
a

array([0.70240422, 0.65642767, 0.38868487, 0.40613288, 0.85756771,
       0.52449964, 0.77800792, 0.32890273, 0.75028909, 0.95656555,
       0.24828801, 0.4873072 , 0.13575261, 0.78794215, 0.03214194,
       0.81382809])

In [32]:
a.ndim  #to check dimensions

1

In [33]:
a.shape

(16,)

In [37]:
a.shape = (2,8)
display(a)

array([[0.70240422, 0.65642767, 0.38868487, 0.40613288, 0.85756771,
        0.52449964, 0.77800792, 0.32890273],
       [0.75028909, 0.95656555, 0.24828801, 0.4873072 , 0.13575261,
        0.78794215, 0.03214194, 0.81382809]])

In [39]:
#Transpose - Convert columns into rows and vice versa
#            changes are temporary.

a.transpose()

array([[0.70240422, 0.75028909],
       [0.65642767, 0.95656555],
       [0.38868487, 0.24828801],
       [0.40613288, 0.4873072 ],
       [0.85756771, 0.13575261],
       [0.52449964, 0.78794215],
       [0.77800792, 0.03214194],
       [0.32890273, 0.81382809]])

In [40]:
a.T   #another way. T for transpose

array([[0.70240422, 0.75028909],
       [0.65642767, 0.95656555],
       [0.38868487, 0.24828801],
       [0.40613288, 0.4873072 ],
       [0.85756771, 0.13575261],
       [0.52449964, 0.78794215],
       [0.77800792, 0.03214194],
       [0.32890273, 0.81382809]])

In [41]:
np.transpose(a) #another way

array([[0.70240422, 0.75028909],
       [0.65642767, 0.95656555],
       [0.38868487, 0.24828801],
       [0.40613288, 0.4873072 ],
       [0.85756771, 0.13575261],
       [0.52449964, 0.78794215],
       [0.77800792, 0.03214194],
       [0.32890273, 0.81382809]])

In [42]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [43]:
x.dtype

dtype('int64')

In [44]:
x.__sizeof__()

152

In [46]:
y = np.array([1,2,3,4,5], dtype = 'object')
y

array([1, 2, 3, 4, 5], dtype=object)

In [48]:
y.dtype

dtype('O')

In [49]:
y.__sizeof__()

152

In [51]:
import pandas as pd

d = pd.read_csv('Weather Data.csv')
print(d)
print(d.describe())

             Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa         

In [52]:
print(d.describe())

            Temp_C  Dew Point Temp_C    Rel Hum_%  Wind Speed_km/h  \
count  8784.000000       8784.000000  8784.000000      8784.000000   
mean      8.798144          2.555294    67.431694        14.945469   
std      11.687883         10.883072    16.918881         8.688696   
min     -23.300000        -28.500000    18.000000         0.000000   
25%       0.100000         -5.900000    56.000000         9.000000   
50%       9.300000          3.300000    68.000000        13.000000   
75%      18.800000         11.800000    81.000000        20.000000   
max      33.000000         24.400000   100.000000        83.000000   

       Visibility_km    Press_kPa  
count    8784.000000  8784.000000  
mean       27.664447   101.051623  
std        12.622688     0.844005  
min         0.200000    97.520000  
25%        24.100000   100.560000  
50%        25.000000   101.070000  
75%        25.000000   101.590000  
max        48.300000   103.650000  


In [53]:
print(d.describe().T)

                   count        mean        std    min     25%     50%  \
Temp_C            8784.0    8.798144  11.687883 -23.30    0.10    9.30   
Dew Point Temp_C  8784.0    2.555294  10.883072 -28.50   -5.90    3.30   
Rel Hum_%         8784.0   67.431694  16.918881  18.00   56.00   68.00   
Wind Speed_km/h   8784.0   14.945469   8.688696   0.00    9.00   13.00   
Visibility_km     8784.0   27.664447  12.622688   0.20   24.10   25.00   
Press_kPa         8784.0  101.051623   0.844005  97.52  100.56  101.07   

                     75%     max  
Temp_C             18.80   33.00  
Dew Point Temp_C   11.80   24.40  
Rel Hum_%          81.00  100.00  
Wind Speed_km/h    20.00   83.00  
Visibility_km      25.00   48.30  
Press_kPa         101.59  103.65  
