<a href="https://colab.research.google.com/github/AmitUdugade/PythonWorkspace/blob/main/Numpy_Part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
e = np.ones((4,4), dtype = bool)
np.fill_diagonal(e, False)
e

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [7]:
~ np.identity(4, dtype = bool)
# ~ Tild sign used for bitwise not operation.
#   if True then convert it in to False and vice versa.

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [10]:
#Indexing Over Numpy -

a = np.arange(1, 25).reshape(6, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [15]:
#Indexing on numpy works on a row.
a[0]

array([1, 2, 3, 4])

In [14]:
#Indexing on numpy works on a row.
a[4]

array([17, 18, 19, 20])

In [18]:
#access 11
a[2][2]

11

In [22]:
a[2, 2]

11

In [20]:
#access 20
a[4][3]

20

In [21]:
#access 6
a[1][1]

6

In [24]:
b = a.reshape(3,4,2)
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [26]:
#access 6
b[0, 2, 1]

6

In [29]:
#access 16
b[1, 3, 1]

16

In [30]:
# Question : is -ve indexing is possible?
# Answer - YES.

b[-1]       #last block will be display

array([[17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [31]:
#Slicing works on a row first.

b[ : ]   # b[start : stop] Row

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [35]:
c = np.arange(1, 25).reshape(6, 4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [36]:
#last 4 rows
c[2:]
'''array([[ 1,  2,  3,  4],           ---- 0
          [ 5,  6,  7,  8],           ---- 1
          [ 9, 10, 11, 12],           ---- 2
          [13, 14, 15, 16],           ---- 3
          [17, 18, 19, 20],           ---- 4
          [21, 22, 23, 24]])          ---- 5
'''

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [38]:
c[1:5]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
#Odd rows
c [::2]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [45]:
#access first and last row
c [::5]

array([[ 1,  2,  3,  4],
       [21, 22, 23, 24]])

In [47]:
c[3::2]

array([[13, 14, 15, 16],
       [21, 22, 23, 24]])

In [48]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [51]:
c[-1: :-2]

array([[21, 22, 23, 24],
       [13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [52]:
#c[rows , Columns]
c[2:4, 1:3]

array([[10, 11],
       [14, 15]])

In [56]:
'''array([[ 7,  8],
       [19, 20]])
'''

c[1: :3, 2:]

array([[ 7,  8],
       [19, 20]])

In [60]:
#Access last column that starting with 4
c[: , -1:]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])

In [61]:
 c[: , 3:]

array([[ 4],
       [ 8],
       [12],
       [16],
       [20],
       [24]])

In [62]:
c[:,-1]  #1D

array([ 4,  8, 12, 16, 20, 24])

In [63]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [66]:
c[::5, 0: :3]

array([[ 1,  4],
       [21, 24]])

In [70]:
c[0:2:2]

array([[1, 2, 3, 4]])