<a href="https://colab.research.google.com/github/AmitUdugade/PythonWorkspace/blob/main/Numpy_Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.arange(1, 25).reshape(4,6)   #Row major

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [3]:
np.arange(1, 25).reshape(4,6, order = 'F')   #Column major

array([[ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23],
       [ 4,  8, 12, 16, 20, 24]])

In [5]:
#Conditional based Selection -
a = np.arange(1, 25).reshape(4,6)

#Performs element-wise operation.
#it will give you array of an boolean output
a>10

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [6]:
a[a>10]  #boolean indexing is supported

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
a[ [True, False, True, False] ]   #fetch odd rows

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [11]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [13]:
#divisible by 5 and 7

a[ (a%5==0) | (a%7==0) ]

array([ 5,  7, 10, 14, 15, 20, 21])

In [14]:
a[ (a%5==0) & (a%10==0)]

array([10, 20])

In [ ]:
#Logical Operator - and , or
#bitwise Operator - &(and), |(or), ~(not), ^(XOR)
'''
XOR
00 0
01 1
10 1
11 0
'''

In [16]:
x = np.array([[2,3], [4,5]])
y = np.array([[10,20], [6,7]])

x>y

array([[False, False],
       [False, False]])

In [18]:
x[x<y]

array([2, 3, 4, 5])

In [19]:
y[x<y]

array([10, 20,  6,  7])

In [20]:
#Scalar Mathematics Over Numpy array :

#add 10 in each element -

x + 10
#Results are temporary as it is arithmatic operator.

array([[12, 13],
       [14, 15]])

In [21]:
#add 10 in each element -

x += 10
#Results are permanent as it is assignment operator.

In [22]:
x

array([[12, 13],
       [14, 15]])

In [23]:
#using np add 100 in each element.

np.add(x, 100)  #Results are temporary.

array([[112, 113],
       [114, 115]])

In [24]:
#addition of x, y [vector addition] -

x + y   #Results are temporary.

array([[22, 33],
       [20, 22]])

In [25]:
np.add(x, y)     #Results are temporary.

array([[22, 33],
       [20, 22]])