<a href="https://colab.research.google.com/github/AmitUdugade/PythonWorkspace/blob/main/Numpy_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.ones((2,2), dtype = str)

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((3,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [ ]:
np.full(2, 100)

array([100, 100])

In [ ]:
np.full((2,2), fill_value = 'NULL')
#in above example (2,2) is a SHAPE.
#and fill_value as a NULL.

array([['NULL', 'NULL'],
       ['NULL', 'NULL']], dtype='<U4')

In [ ]:
#Identity() : Identity Matrix
# Diagonal element is 1 and non-diagonal element is 0
#identity(n)
#Here n = n * n

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.identity((2,2))  # Throws an TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [ ]:
#change the diagonal position with k -
np.eye(4,6, k=3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#Identity() vs eye() -
'''
    identity() - No. of rows and no. columns are same.
    eye() - we can chnage the no. of rows and columns and also can change the diagonal position by using [parameter - k].
'''


In [ ]:
''' def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.

    Returns num evenly spaced samples, calculated over the
    interval [start, stop].

    The endpoint of the interval can optionally be excluded.

    Parameters:
      startarray_like
      The starting value of the sequence.

      stoparray_like
      The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples,
      so that stop is excluded. Note that the step size changes when endpoint is False.

      numint, optional
      Number of samples to generate. Default is 50. Must be non-negative.

      endpointbool, optional
      If True, stop is the last sample. Otherwise, it is not included. Default is True.

      retstepbool, optional
      If True, return (samples, step), where step is the spacing between samples.

      dtypedtype, optional
      The type of the output array. If dtype is not given, the data type is inferred from start and stop.
      The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.

'''

np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(2, 10, retstep = True)

(array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
         2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
         3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
         4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
         5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
         6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
         6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
         7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
         8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
         9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ]),
 0.16326530612244897)

In [ ]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
1/50

0.02

In [10]:
#RandInt() -
''' Random Integer Values.
    randint(low, high=none, size=none, dtype=int)
    returns random integers from low('inclusive') to high('exclusive')
'''

import numpy as np
np.random.randint(4)

3

In [6]:
np.random.randint(4, size=10)     #when we supply single values then low is exclusive.

array([3, 0, 3, 1, 0, 1, 3, 3, 3, 1])

In [ ]:
#np.random.randint((4,5), size=10)    #Getting an ValueError: shape mismatch: objects cannot be broadcast to a single shape.

In [11]:
np.random.randint(4,10, 12)    #when we supply two values then high is exclusive.

array([4, 4, 5, 4, 7, 5, 8, 6, 7, 6, 4, 6])

In [12]:
#generate a data of blood pressure in range 80, 120.

np.random.randint(80, 121, size = 50)         #high is 121 because 120 is still in a normal range. and patient size is 50.

array([110, 114, 106, 119, 111,  90,  99,  94, 119, 105, 109,  98,  85,
        93, 115,  99, 106, 115, 115, 115,  86,  96, 104, 118, 116,  96,
        87, 103,  80, 101, 114, 114,  81, 120, 103,  96,  91,  86, 119,
        83,  96,  89,  83, 102,  92, 109, 116,  91, 102, 107])

In [13]:
#salary data : 20000, 60000 for 100 employees

np.random.randint(20000, 60000, 100)

array([35437, 22429, 38169, 57604, 36992, 40263, 57211, 44998, 39843,
       33312, 29985, 50244, 39343, 21364, 32024, 50386, 41604, 38266,
       56413, 52496, 23647, 50662, 21840, 25928, 36209, 34585, 52077,
       33691, 40418, 32034, 58882, 30765, 28553, 35509, 38649, 38214,
       47888, 25514, 53155, 57788, 57694, 49661, 25178, 20537, 43317,
       40190, 23750, 39095, 51200, 39033, 50676, 56852, 44946, 58772,
       51481, 37619, 35314, 44463, 59572, 28329, 49484, 25108, 38646,
       56680, 30946, 24353, 40852, 55970, 27391, 47484, 52804, 53834,
       44297, 58787, 44623, 55410, 36235, 26115, 39412, 35840, 42241,
       41690, 35138, 24600, 46327, 32389, 55268, 45619, 38661, 37984,
       41004, 32416, 46112, 29922, 38555, 58363, 44693, 56302, 36259,
       32580])

In [15]:
''' If we have an array in a memory.
    and want to create a new array with same structure
'''

x = np.random.random((4,3))
print(x)

[[0.53011527 0.72261746 0.95012539]
 [0.7194011  0.13435362 0.76635781]
 [0.0106001  0.12206554 0.8312869 ]
 [0.17245824 0.04123827 0.2414408 ]]


In [16]:
x.shape

(4, 3)

In [17]:
#create a 1's array having same structure as 'x'

np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros_like(x)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.empty_like(x, dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
#Typecasting in NUMPY() -
#Typecasting - Implicit, Explicit

np.arange(5)

array([0, 1, 2, 3, 4])

In [24]:
np.arange(5).dtype

dtype('int64')

In [25]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [26]:
np.arange(5, dtype=float).dtype

dtype('float64')

In [27]:
np.arange(5, dtype='float16')

array([0., 1., 2., 3., 4.], dtype=float16)

In [28]:
np.arange(5, dtype='float16').dtype

dtype('float16')

In [ ]:
# np.arange(5223455616432222332, dtype='float16')        - ValueError: array is too big

In [31]:
np.arange(20, dtype = 'f8')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [32]:
np.arange(20, dtype = 'f8').dtype      #8 bytes

dtype('float64')

In [33]:
np.arange(20, dtype = 'float32').dtype      #32 bits

dtype('float32')

In [49]:
# After Creation of an array : if we want to TYPECAST

s = np.arange(10)
print(s)
print("Before Conversion ", s.dtype)
s1 = s.astype('i4')
print("After Conversion ", s1.dtype)
s2 = s.astype(str)
print(s2)
print("After Conversion in string ", s2.dtype)

[0 1 2 3 4 5 6 7 8 9]
Before Conversion  int64
After Conversion  int32
['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
After Conversion in string  <U21


In [55]:
np.arange(5).dtype

dtype('int64')

In [59]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S